# Generated by Django 3.2.9 on 2021-11-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListTask',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.task')),
                ('data', models.DateField(verbose_name='Data')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='name',
            field=models.CharField(choices=[('Su', 'Sunday'), ('Sa', 'Saturday'), ('We', 'Wednesday'), ('Fr', 'Friday'), ('Tu', 'Tuesday'), ('Th', 'Thursday'), ('Mo', 'Monday')], max_length=2, verbose_name='Day'),
        ),
    ]
