# Generated by Django 3.2.9 on 2021-11-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211120_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='name',
            field=models.CharField(choices=[('Fr', 'Friday'), ('Sa', 'Saturday'), ('Th', 'Thursday'), ('Su', 'Sunday'), ('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday')], max_length=2, verbose_name='Day'),
        ),
        migrations.DeleteModel(
            name='ListTask',
        ),
    ]
