# Generated by Django 3.2.9 on 2021-11-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_timetable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='name',
            field=models.CharField(choices=[('Tu', 'Tuesday'), ('Th', 'Thursday'), ('We', 'Wednesday'), ('Fr', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday'), ('Mo', 'Monday')], max_length=2, verbose_name='Day'),
        ),
    ]
