# Generated by Django 3.2.9 on 2021-11-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Task')),
                ('time', models.DateTimeField(verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sa', 'Saturday'), ('Su', 'Sunday'), ('Tu', 'Tuesday'), ('Mo', 'Monday'), ('Fr', 'Friday'), ('Th', 'Thursday'), ('We', 'Wednesday')], max_length=2, verbose_name='Day')),
                ('task', models.ManyToManyField(to='main.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('finish', models.DateTimeField(verbose_name='Finish')),
                ('planed', models.DateTimeField(verbose_name='Planed')),
                ('fact', models.DateTimeField(verbose_name='Fact')),
                ('task', models.ManyToManyField(to='main.Task')),
            ],
        ),
    ]
