# Generated by Django 3.2.9 on 2021-11-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211121_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='name',
            field=models.CharField(choices=[('Tu', 'Tuesday'), ('Fr', 'Friday'), ('Th', 'Thursday'), ('Mo', 'Monday'), ('Su', 'Sunday'), ('Sa', 'Saturday'), ('We', 'Wednesday')], max_length=2, verbose_name='Day'),
        ),
    ]
