# Generated by Django 3.2.9 on 2021-11-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_timetable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='finish',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Finish'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='name',
            field=models.CharField(choices=[('Su', 'Sunday'), ('Sa', 'Saturday'), ('Mo', 'Monday'), ('Fr', 'Friday'), ('We', 'Wednesday'), ('Tu', 'Tuesday'), ('Th', 'Thursday')], max_length=2, verbose_name='Day'),
        ),
    ]
